[package]
name = "libtz"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/caldwell/libtz"
description = "WIP. Coming soon, hopefully"

[lib]
path = "lib.rs"

[dependencies]
libtz-sys = "0.2"

[dev-dependencies]
version-sync = "0.9"
