[package]
name = "libtz"
version = "0.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/caldwell/libtz"
description = "WIP. Coming soon, hopefully"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
